# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_link',
            field=models.CharField(default=models.CharField(max_length=30, unique=True, verbose_name='Login'), max_length=55, verbose_name='Avatar path'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=30, unique=True, verbose_name='Login'),
        ),
    ]
