# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20170421_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.BooleanField(choices=[(0, '+'), (1, '-')], verbose_name='Delta')),
            ],
            options={
                'verbose_name': 'Element rate(answer)',
                'verbose_name_plural': 'Element rate(answer)',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True, verbose_name='Login')),
                ('email', models.EmailField(max_length=35, unique=True, verbose_name='Email')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('avatar_link', models.CharField(default=models.CharField(max_length=30, unique=True, verbose_name='Login'), max_length=55, verbose_name='Avatar path')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.BooleanField(choices=[(0, '+'), (1, '-')], verbose_name='Delta rate')),
            ],
            options={
                'verbose_name': 'Element rate (question)',
                'verbose_name_plural': 'Elements ratings (question)',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='tag title'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='questionrating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='Rated element (question>'),
        ),
        migrations.AddField(
            model_name='questionrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerrating',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer', verbose_name='Rated element(answer'),
        ),
        migrations.AddField(
            model_name='answerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
        ),
    ]
