# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170523_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_link',
            field=models.CharField(default='no_avatar.jpg', max_length=55, verbose_name='Avatar path'),
        ),
    ]
